version: '2'

services:
  express:
    image: docker.io/bitnami/express:4
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - './html:/app'
